language: python

python:
  - "3.9"
  - "pypy"
  - "pypy3"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[dev]
  - pip install tox-travis

script:
  - tox
